[config]
timeout = 5

[config.retry_params]
total = 5
backoff_factor = 0
status_forcelist = [429, 500, 502, 503, 504]
method_whitelist = ["HEAD", "GET", "OPTIONS"]

[config.async_retry_params]
total = 5
backoff_factor = 0
status_forcelist = [429, 500, 502, 503, 504]
method_whitelist = ["HEAD", "GET", "OPTIONS"]
